force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Commission</label>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Commision_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commision_Amount__c</fullName>
    <label>Commision Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadHelper.cls
public class LeadHelper {

    
    public static Integer leadCommission(String LeadId)
    {
        Integer Commission = 0;
        List<Lead> leadRecord = [Select Lead_Generator__C from
            			Lead Where Id =:LeadId];
        System.debug(leadRecord);
       
        if(!leadRecord.IsEmpty())
        {
            List<User> userRecord = [Select profileId, Profile.Name
                from User where Id = :leadRecord[0].Lead_Generator__c];
            if(!userRecord.isEmpty())
            {
               Commission =  (Integer)Commission__c.getInstance
                   			(userRecord[0].ProfileId).Commision_Amount__c;
            }
        }
        return Commission;
      }
}