force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>Dep-{0000}</displayFormat>
        <label>DepartmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Employee details</description>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>EmployeeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>Employee&apos;s Dept name lookup to dept</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <description>Employee&apos;s Name</description>
    <label>Employee Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Employee&apos;s Gender</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RelationshipChildtoParentSTOS.cls
public class RelationshipChildtoParentSTOS {
    
    public static void contacttoAccounttoUser()
    {
        List<Contact> conRecord = [Select LastName, Account.Name, Account.Owner.Name from Contact];
        
        for(Contact con :conRecord)
        {
            system.debug('Contact Name :' +con.LastName);
            system.debug('Account Name :' +con.Account.Name);
            system.debug('Owner Name :' +con.Account.Owner.Name);
            
        }
        
    }

    public static void deptToAccounttoOwner()
        // Custom to Standard Object Relationship Child to Parent
    {
        List<Department__c> depList = 
            					[Select Name, Account__r.Name, Account__r.Owner.Name 
                                 from Department__c
                                 Where Account__c!=null];
        
        for(Department__c depRecord:depList)
        {
            system.debug('Department Name :' +depRecord.Name);
            system.debug('Account Name :' +depRecord.Account__r.Name);
            system.debug('Owner Name :' +depRecord.Account__r.Owner.Name);
            
        }
    }
    
    public static void getemployeesdepartment()
    {
        List<Employee__C> empList = 
            [select Employee_Name__c, Gender__C,Department__r.Name 
             from Employee__C];
       
        for(Employee__c empRecord:empList)
        {
            system.debug('Employee Name :' +empRecord.Employee_Name__c);
            system.debug('Gender :' +empRecord.Gender__C);
            system.debug('Department Name :' +empRecord.Department__r.Name);
            
        }
    }
}