force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>Dep-{0000}</displayFormat>
        <label>DepartmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Department&apos;s Location</description>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelationshipPTOCStandard.cls
public class RelationshipPTOCStandard {
    
    //Get Account with contact Names relationship SOQL Std to custom Object
    
    public static void getAccountNameswithContacts()
    {
        List<Account> accountList = [Select Name,(Select LastName from contacts) from
                                	Account];
        for(Account accRecord:accountList)
        {
            system.debug('AccountName :' +accRecord.Name);
            system.debug('======= Contacts are =======');
                         
            for(Contact conRecord:accRecord.contacts)
            {
                system.debug(conRecord.LastName);
            }
        }
    }
     public static void getAccountwithDepartments()
     {
         List<Account> accountList = [Select Name,
                                     (Select Name, Location__c from Departments__r)from Account];
         for(Account accRecord:accountList)
         {
             system.debug(accRecord.Name);
             for(Department__C depRecord:accRecord.Departments__r)
             {
                 system.debug('Department info: ' +depRecord.Name +' ' +depRecord.Location__c);
             }
                 
         }
     }


}